GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Hello"
}

###

DELETE http://localhost:3001/todo/delete/64be9905cefd85c112d2cf3e

###

PUT http://localhost:3001/todo/complete/64be9b780b97a060fd0c5e41